[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_turbine = "C9VNgETz1HMM1G73aVT6b1KVFG2ag1yBQ4PKXuwiCFm5"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
